path0:
  - changed-files:
    - any-glob-to-any-file: "path0/**"
    #    head-branch: [ "^ALMA-" ]
    base-branch: 'main'

path1:
  - changed-files:
    - any-glob-to-any-file: "path1/**"
    head-branch: [ "^ALMA-" ]
    base-branch: 'main'